from typing import Dict, Callable, Any


def compile(definition: Dict) -> Callable[[Dict[str, Any]], Dict[str, Any]]: ...

class JsonSchemaException(Exception): ...
class JsonSchemaDefinitionException(JsonSchemaException): ...
class JsonSchemaValueException(JsonSchemaException):
    @property
    def message(self) -> str: ...
