name: "wiki"

on:
  push:
    paths:
      - "docs/**"

jobs:
  deploy:
    name: "Deploy docs to wiki"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Deploy to Wiki"
        uses: "joeizzard/action-wiki-sync@master"
        with:
          username: "fastybird"
          access_token: ${{ secrets.GITHUB_TOKEN }}
          wiki_folder: "docs"
          commit_username: "FastyBird"
          commit_email: "code@fastybird.com"
          commit_message: "action: wiki sync"
